# Generated by Django 2.0.2 on 2018-09-20 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField()),
                ('body', models.TextField()),
                ('url', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('exchange_choices', models.CharField(choices=[('FREE', 'Free'), ('PAID', 'Paid'), ('BARTER', 'Barter')], max_length=100)),
                ('status_choices', models.CharField(choices=[('OPEN', 'Open'), ('PENDING', 'Pending'), ('EXCHANGED', 'Exchange')], max_length=100)),
                ('condition_choices', models.CharField(choices=[('NEW', 'New'), ('USED_NEW', 'Used but it is like new'), ('USED_GOOD', 'Used but good'), ('USED_JADED', 'Used and jaded')], max_length=100)),
                ('original_poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
