# Generated by Django 2.1.3 on 2018-11-17 23:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField()),
                ('body', models.TextField()),
                ('url', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('book_price', models.FloatField(default=0)),
                ('exchange_choices', models.CharField(choices=[('FR', 'Free'), ('PA', 'Paid'), ('BA', 'Barter')], max_length=100)),
                ('condition_choices', models.CharField(choices=[('NE', 'New - Never Used'), ('UN', 'Used but seems still new'), ('UG', 'Used but in good conditions'), ('UJ', 'Used and you can see it')], max_length=100)),
                ('status_choices', models.CharField(choices=[('OP', 'Open to trade'), ('PE', 'Pending for approval'), ('EX', 'Exhanged already')], default='OP', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('preference1', models.CharField(choices=[('Science fiction', 'Science fiction'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Travel', 'Travel'), ('Satire', 'Satire'), ('Religion', 'Religion'), ('History', 'History'), ('Science', 'Science'), ('Poetry', 'Poetry'), ('Encyclopedias', 'Encyclopedias'), ('Dictionaries', 'Dictionaries'), ('Comics', 'Comics'), ('Art', 'Art'), ('Cookbooks', 'Cookbooks'), ('Diaries', 'Diaries'), ('Journals', 'Journals'), ('Prayer', 'Prayer'), ('Series', 'Series'), ('Biographies', 'Biographies'), ('Fantasy', 'Fantasy')], default='Science fiction', max_length=100, null=True)),
                ('preference2', models.CharField(choices=[('Science fiction', 'Science fiction'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Travel', 'Travel'), ('Satire', 'Satire'), ('Religion', 'Religion'), ('History', 'History'), ('Science', 'Science'), ('Poetry', 'Poetry'), ('Encyclopedias', 'Encyclopedias'), ('Dictionaries', 'Dictionaries'), ('Comics', 'Comics'), ('Art', 'Art'), ('Cookbooks', 'Cookbooks'), ('Diaries', 'Diaries'), ('Journals', 'Journals'), ('Prayer', 'Prayer'), ('Series', 'Series'), ('Biographies', 'Biographies'), ('Fantasy', 'Fantasy')], default='Satire', max_length=100, null=True)),
                ('preference3', models.CharField(choices=[('Science fiction', 'Science fiction'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Travel', 'Travel'), ('Satire', 'Satire'), ('Religion', 'Religion'), ('History', 'History'), ('Science', 'Science'), ('Poetry', 'Poetry'), ('Encyclopedias', 'Encyclopedias'), ('Dictionaries', 'Dictionaries'), ('Comics', 'Comics'), ('Art', 'Art'), ('Cookbooks', 'Cookbooks'), ('Diaries', 'Diaries'), ('Journals', 'Journals'), ('Prayer', 'Prayer'), ('Series', 'Series'), ('Biographies', 'Biographies'), ('Fantasy', 'Fantasy')], default='Travel', max_length=100, null=True)),
                ('preference4', models.CharField(choices=[('Science fiction', 'Science fiction'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Travel', 'Travel'), ('Satire', 'Satire'), ('Religion', 'Religion'), ('History', 'History'), ('Science', 'Science'), ('Poetry', 'Poetry'), ('Encyclopedias', 'Encyclopedias'), ('Dictionaries', 'Dictionaries'), ('Comics', 'Comics'), ('Art', 'Art'), ('Cookbooks', 'Cookbooks'), ('Diaries', 'Diaries'), ('Journals', 'Journals'), ('Prayer', 'Prayer'), ('Series', 'Series'), ('Biographies', 'Biographies'), ('Fantasy', 'Fantasy')], default='Cookbooks', max_length=100, null=True)),
                ('preference5', models.CharField(choices=[('Science fiction', 'Science fiction'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Travel', 'Travel'), ('Satire', 'Satire'), ('Religion', 'Religion'), ('History', 'History'), ('Science', 'Science'), ('Poetry', 'Poetry'), ('Encyclopedias', 'Encyclopedias'), ('Dictionaries', 'Dictionaries'), ('Comics', 'Comics'), ('Art', 'Art'), ('Cookbooks', 'Cookbooks'), ('Diaries', 'Diaries'), ('Journals', 'Journals'), ('Prayer', 'Prayer'), ('Series', 'Series'), ('Biographies', 'Biographies'), ('Fantasy', 'Fantasy')], default='Religion', max_length=100, null=True)),
                ('birth_date', models.DateField(default=datetime.date(1995, 7, 12), null=True)),
                ('gender', models.CharField(choices=[('m', 'Masculine'), ('f', 'Feminine'), ('o', 'Other')], default='Masculine', max_length=1, null=True)),
                ('location', models.CharField(default='London, Fulham', max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='original_poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
