# Generated by Django 2.0.2 on 2018-09-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status_choices',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PENDING', 'Pending'), ('EXCHANGED', 'Exchange')], default='OPEN', max_length=100),
        ),
    ]
