# Generated by Django 2.0.2 on 2018-09-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180920_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_price',
            field=models.FloatField(default=0),
        ),
    ]
