# Generated by Django 2.1.3 on 2018-11-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition_choices',
            field=models.CharField(choices=[('New', 'New - Never Used'), ('Used but new', 'Used but seems still new'), ('Used but good', 'Used but in good conditions'), ('Used jaded', 'Used and you can see it')], max_length=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='exchange_choices',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid'), ('Barter', 'Barter')], max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='status_choices',
            field=models.CharField(choices=[('Open', 'Open to trade'), ('Pending', 'Pending for approval'), ('Exchanged', 'Exhanged already')], default='Open', max_length=2),
        ),
    ]
