# Generated by Django 2.1.3 on 2018-11-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20181110_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition_choices',
            field=models.CharField(choices=[('NE', 'New - Never Used'), ('UN', 'Used but seems still new'), ('UG', 'Used but in good conditions'), ('UJ', 'Used and you can see it')], max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='exchange_choices',
            field=models.CharField(choices=[('FR', 'Free'), ('PA', 'Paid'), ('BA', 'Barter')], max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='status_choices',
            field=models.CharField(choices=[('OP', 'Open to trade'), ('PE', 'Pending for approval'), ('EX', 'Exhanged already')], default='OP', max_length=100),
        ),
    ]
