# Generated by Django 2.1.3 on 2018-11-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20181110_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition_choices',
            field=models.CharField(choices=[('NE', 'New - Never Used'), ('UN', 'Used but seems still new'), ('UG', 'Used but in good conditions'), ('UJ', 'Used and you can see it')], max_length=100),
        ),
    ]
