# Generated by Django 2.1.3 on 2018-11-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20181110_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status_choices',
            field=models.CharField(choices=[('ssss', 'Open to trade'), ('PE', 'Pending for approval'), ('EX', 'Exhanged already')], default='ssss', max_length=100),
        ),
    ]
