# Generated by Django 2.1.3 on 2018-11-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='college',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='major',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='genre',
            field=models.CharField(choices=[('m', 'Masculine'), ('f', 'Feminine')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preference1',
            field=models.CharField(choices=[('Science fiction', 'Science fiction'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Travel', 'Travel'), ('Satire', 'Satire'), ('Religion', 'Religion'), ('History', 'History'), ('Science', 'Science'), ('Poetry', 'Poetry'), ('Encyclopedias', 'Encyclopedias'), ('Dictionaries', 'Dictionaries'), ('Comics', 'Comics'), ('Art', 'Art'), ('Cookbooks', 'Cookbooks'), ('Diaries', 'Diaries'), ('Journals', 'Journals'), ('Prayer', 'Prayer'), ('Series', 'Series'), ('Biographies', 'Biographies'), ('Fantasy', 'Fantasy')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preference2',
            field=models.CharField(choices=[('Science fiction', 'Science fiction'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Travel', 'Travel'), ('Satire', 'Satire'), ('Religion', 'Religion'), ('History', 'History'), ('Science', 'Science'), ('Poetry', 'Poetry'), ('Encyclopedias', 'Encyclopedias'), ('Dictionaries', 'Dictionaries'), ('Comics', 'Comics'), ('Art', 'Art'), ('Cookbooks', 'Cookbooks'), ('Diaries', 'Diaries'), ('Journals', 'Journals'), ('Prayer', 'Prayer'), ('Series', 'Series'), ('Biographies', 'Biographies'), ('Fantasy', 'Fantasy')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preference3',
            field=models.CharField(choices=[('Science fiction', 'Science fiction'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Travel', 'Travel'), ('Satire', 'Satire'), ('Religion', 'Religion'), ('History', 'History'), ('Science', 'Science'), ('Poetry', 'Poetry'), ('Encyclopedias', 'Encyclopedias'), ('Dictionaries', 'Dictionaries'), ('Comics', 'Comics'), ('Art', 'Art'), ('Cookbooks', 'Cookbooks'), ('Diaries', 'Diaries'), ('Journals', 'Journals'), ('Prayer', 'Prayer'), ('Series', 'Series'), ('Biographies', 'Biographies'), ('Fantasy', 'Fantasy')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preference4',
            field=models.CharField(choices=[('Science fiction', 'Science fiction'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Travel', 'Travel'), ('Satire', 'Satire'), ('Religion', 'Religion'), ('History', 'History'), ('Science', 'Science'), ('Poetry', 'Poetry'), ('Encyclopedias', 'Encyclopedias'), ('Dictionaries', 'Dictionaries'), ('Comics', 'Comics'), ('Art', 'Art'), ('Cookbooks', 'Cookbooks'), ('Diaries', 'Diaries'), ('Journals', 'Journals'), ('Prayer', 'Prayer'), ('Series', 'Series'), ('Biographies', 'Biographies'), ('Fantasy', 'Fantasy')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preference5',
            field=models.CharField(choices=[('Science fiction', 'Science fiction'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Travel', 'Travel'), ('Satire', 'Satire'), ('Religion', 'Religion'), ('History', 'History'), ('Science', 'Science'), ('Poetry', 'Poetry'), ('Encyclopedias', 'Encyclopedias'), ('Dictionaries', 'Dictionaries'), ('Comics', 'Comics'), ('Art', 'Art'), ('Cookbooks', 'Cookbooks'), ('Diaries', 'Diaries'), ('Journals', 'Journals'), ('Prayer', 'Prayer'), ('Series', 'Series'), ('Biographies', 'Biographies'), ('Fantasy', 'Fantasy')], max_length=100, null=True),
        ),
    ]
