# Generated by Django 2.1.3 on 2018-11-17 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20181117_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(default=datetime.date(2015, 1, 1), null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preference1',
            field=models.CharField(choices=[('Science fiction', 'Science fiction'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Travel', 'Travel'), ('Satire', 'Satire'), ('Religion', 'Religion'), ('History', 'History'), ('Science', 'Science'), ('Poetry', 'Poetry'), ('Encyclopedias', 'Encyclopedias'), ('Dictionaries', 'Dictionaries'), ('Comics', 'Comics'), ('Art', 'Art'), ('Cookbooks', 'Cookbooks'), ('Diaries', 'Diaries'), ('Journals', 'Journals'), ('Prayer', 'Prayer'), ('Series', 'Series'), ('Biographies', 'Biographies'), ('Fantasy', 'Fantasy')], default='Science fiction', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preference2',
            field=models.CharField(choices=[('Science fiction', 'Science fiction'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Travel', 'Travel'), ('Satire', 'Satire'), ('Religion', 'Religion'), ('History', 'History'), ('Science', 'Science'), ('Poetry', 'Poetry'), ('Encyclopedias', 'Encyclopedias'), ('Dictionaries', 'Dictionaries'), ('Comics', 'Comics'), ('Art', 'Art'), ('Cookbooks', 'Cookbooks'), ('Diaries', 'Diaries'), ('Journals', 'Journals'), ('Prayer', 'Prayer'), ('Series', 'Series'), ('Biographies', 'Biographies'), ('Fantasy', 'Fantasy')], default='Satire', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preference3',
            field=models.CharField(choices=[('Science fiction', 'Science fiction'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Travel', 'Travel'), ('Satire', 'Satire'), ('Religion', 'Religion'), ('History', 'History'), ('Science', 'Science'), ('Poetry', 'Poetry'), ('Encyclopedias', 'Encyclopedias'), ('Dictionaries', 'Dictionaries'), ('Comics', 'Comics'), ('Art', 'Art'), ('Cookbooks', 'Cookbooks'), ('Diaries', 'Diaries'), ('Journals', 'Journals'), ('Prayer', 'Prayer'), ('Series', 'Series'), ('Biographies', 'Biographies'), ('Fantasy', 'Fantasy')], default='Travel', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preference4',
            field=models.CharField(choices=[('Science fiction', 'Science fiction'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Travel', 'Travel'), ('Satire', 'Satire'), ('Religion', 'Religion'), ('History', 'History'), ('Science', 'Science'), ('Poetry', 'Poetry'), ('Encyclopedias', 'Encyclopedias'), ('Dictionaries', 'Dictionaries'), ('Comics', 'Comics'), ('Art', 'Art'), ('Cookbooks', 'Cookbooks'), ('Diaries', 'Diaries'), ('Journals', 'Journals'), ('Prayer', 'Prayer'), ('Series', 'Series'), ('Biographies', 'Biographies'), ('Fantasy', 'Fantasy')], default='Cookbooks', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preference5',
            field=models.CharField(choices=[('Science fiction', 'Science fiction'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Travel', 'Travel'), ('Satire', 'Satire'), ('Religion', 'Religion'), ('History', 'History'), ('Science', 'Science'), ('Poetry', 'Poetry'), ('Encyclopedias', 'Encyclopedias'), ('Dictionaries', 'Dictionaries'), ('Comics', 'Comics'), ('Art', 'Art'), ('Cookbooks', 'Cookbooks'), ('Diaries', 'Diaries'), ('Journals', 'Journals'), ('Prayer', 'Prayer'), ('Series', 'Series'), ('Biographies', 'Biographies'), ('Fantasy', 'Fantasy')], default='Religion', max_length=100, null=True),
        ),
    ]
