# Generated by Django 2.1.3 on 2018-11-17 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20181117_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='original_poster',
            new_name='user',
        ),
    ]
