# Generated by Django 2.1.3 on 2018-11-17 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20181117_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(default=datetime.date(1995, 7, 12), null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='genre',
            field=models.CharField(choices=[('m', 'Masculine'), ('f', 'Feminine')], default='m', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='London, Fulham', max_length=150, null=True),
        ),
    ]
